/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';
import { TypeDestination } from './typeDestination';

/**
* Destination for \"Value for Value\" payment. 
*/
export class DestinationV4v {
    /**
    * Name for the destination 
    */
    'name'?: string;
    /**
    * Address of node to receive payment 
    */
    'address'?: string;
    'type'?: TypeDestination;
    /**
    * Share of payment the destination should receive 
    */
    'split'?: number;
    /**
    * Indicates if destination is included due to a fee being charged 
    */
    'fee'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TypeDestination"
        },
        {
            "name": "split",
            "baseName": "split",
            "type": "number"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DestinationV4v.attributeTypeMap;
    }
}

