/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';

/**
* Is episode marked as explicit    - 0: not marked explicit   - 1: marked explicit 
*/
export enum Explicit {
    NUMBER_0 = <any> 0,
    NUMBER_1 = <any> 1
}
