/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';
import { Locked } from './locked';
import { Type } from './type';

export class FeedSearch {
    /**
    * The internal PodcastIndex.org Feed ID. 
    */
    'id'?: number;
    /**
    * Name of the feed 
    */
    'title'?: string;
    /**
    * Current feed URL 
    */
    'url'?: string;
    /**
    * The URL of the feed, before it changed to the current `url` value. 
    */
    'originalUrl'?: string;
    /**
    * The channel-level link in the feed 
    */
    'link'?: string;
    /**
    * The channel-level description 
    */
    'description'?: string;
    /**
    * The channel-level author element.  Usually iTunes specific, but could be from another namespace if not present. 
    */
    'author'?: string;
    /**
    * The channel-level owner:name element.  Usually iTunes specific, but could be from another namespace if not present. 
    */
    'ownerName'?: string;
    /**
    * The channel-level image element. 
    */
    'image'?: string;
    /**
    * The seemingly best artwork we can find for the feed. Might be the same as `image` in most instances. 
    */
    'artwork'?: string;
    /**
    * The channel-level pubDate for the feed, if it’s sane. If not, this is a heuristic value, arrived at by analyzing other parts of the feed, like item-level pubDates. 
    */
    'lastUpdateTime'?: number;
    /**
    * The last time we attempted to pull this feed from its url. 
    */
    'lastCrawlTime'?: number;
    /**
    * The last time we tried to parse the downloaded feed content. 
    */
    'lastParseTime'?: number;
    /**
    * Timestamp of the last time we got a \"good\", meaning non-4xx/non-5xx, status code when pulling this feed from its url. 
    */
    'lastGoodHttpStatusTime'?: number;
    /**
    * The last http status code we got when pulling this feed from its url.  You will see some made up status codes sometimes. These are what we use to track state within the feed puller. These all start with 9xx. 
    */
    'lastHttpStatus'?: number;
    /**
    * The Content-Type header from the last time we pulled this feed from its url. 
    */
    'contentType'?: string;
    /**
    * The iTunes ID of this feed if there is one, and we know what it is. 
    */
    'itunesId'?: number;
    /**
    * The channel-level generator element if there is one. 
    */
    'generator'?: string;
    /**
    * The channel-level language specification of the feed. Languages accord with the [RSS Language Spec](https://www.rssboard.org/rss-language-codes). 
    */
    'language'?: string;
    'type'?: Type;
    /**
    * At some point, we give up trying to process a feed and mark it as dead. This is usually after 1000 errors without a successful pull/parse cycle. Once the feed is marked dead, we only check it once per month. 
    */
    'dead'?: number;
    /**
    * The number of errors we’ve encountered trying to pull a copy of the feed. Errors are things like a 500 or 404 response, a server timeout, bad encoding, etc. 
    */
    'crawlErrors'?: number;
    /**
    * The number of errors we’ve encountered trying to parse the feed content. Errors here are things like not well-formed xml, bad character encoding, etc.  We fix many of these types of issues on the fly when parsing. We only increment the errors count when we can’t fix it. 
    */
    'parseErrors'?: number;
    /**
    * An array of categories, where the index is the Category ID and the value is the Category Name.  Category numbers and names can be found in the [Podcast Namespace documentation](https://github.com/Podcastindex-org/podcast-namespace/blob/main/categories.json) 
    */
    'categories'?: object;
    'locked'?: Locked;
    /**
    * A CRC32 hash of the `image` URL with the protocol (`http://`, `https://`) removed. Can be used to retrieve a resized/converted version of the image specified by `image` from https://podcastimages.com/.  Using the format: `https://podcastimages.com/<hash>_<size>.jpg` Replace `<hash>` with the value in this field. The `<size>` is the desired image width/height. Ex: `https://podcastimages.com/1011338142_600.jpg`  **Work in Progress**: the `podcastimages.com` system is currently not working. 
    */
    'imageUrlHash'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "originalUrl",
            "baseName": "originalUrl",
            "type": "string"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string"
        },
        {
            "name": "ownerName",
            "baseName": "ownerName",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "artwork",
            "baseName": "artwork",
            "type": "string"
        },
        {
            "name": "lastUpdateTime",
            "baseName": "lastUpdateTime",
            "type": "number"
        },
        {
            "name": "lastCrawlTime",
            "baseName": "lastCrawlTime",
            "type": "number"
        },
        {
            "name": "lastParseTime",
            "baseName": "lastParseTime",
            "type": "number"
        },
        {
            "name": "lastGoodHttpStatusTime",
            "baseName": "lastGoodHttpStatusTime",
            "type": "number"
        },
        {
            "name": "lastHttpStatus",
            "baseName": "lastHttpStatus",
            "type": "number"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "string"
        },
        {
            "name": "itunesId",
            "baseName": "itunesId",
            "type": "number"
        },
        {
            "name": "generator",
            "baseName": "generator",
            "type": "string"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Type"
        },
        {
            "name": "dead",
            "baseName": "dead",
            "type": "number"
        },
        {
            "name": "crawlErrors",
            "baseName": "crawlErrors",
            "type": "number"
        },
        {
            "name": "parseErrors",
            "baseName": "parseErrors",
            "type": "number"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "object"
        },
        {
            "name": "locked",
            "baseName": "locked",
            "type": "Locked"
        },
        {
            "name": "imageUrlHash",
            "baseName": "imageUrlHash",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return FeedSearch.attributeTypeMap;
    }
}

