/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';

export class FeedTrending {
    /**
    * The internal PodcastIndex.org Feed ID. 
    */
    'id'?: number;
    /**
    * Current feed URL 
    */
    'url'?: string;
    /**
    * Name of the feed 
    */
    'title'?: string;
    /**
    * The channel-level author element.  Usually iTunes specific, but could be from another namespace if not present. 
    */
    'author'?: string;
    /**
    * The channel-level image element. 
    */
    'image'?: string;
    /**
    * The date and time the most recent episode in the feed was published 
    */
    'newestItemPublishedTime'?: number;
    /**
    * The iTunes ID of this feed if there is one, and we know what it is. 
    */
    'itunesId'?: number;
    /**
    * The ranking for how the podcast is trending in the index 
    */
    'trendScore'?: number;
    /**
    * The channel-level language specification of the feed. Languages accord with the [RSS Language Spec](https://www.rssboard.org/rss-language-codes). 
    */
    'language'?: string;
    /**
    * An array of categories, where the index is the Category ID and the value is the Category Name.  Category numbers and names can be found in the [Podcast Namespace documentation](https://github.com/Podcastindex-org/podcast-namespace/blob/main/categories.json) 
    */
    'categories'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "newestItemPublishedTime",
            "baseName": "newestItemPublishedTime",
            "type": "number"
        },
        {
            "name": "itunesId",
            "baseName": "itunesId",
            "type": "number"
        },
        {
            "name": "trendScore",
            "baseName": "trendScore",
            "type": "number"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return FeedTrending.attributeTypeMap;
    }
}

