/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';

/**
* Information for donation/funding the podcast.  See the [podcast namespace spec](https://podcastindex.org/namespace/1.0#funding) for more information. 
*/
export class Funding {
    /**
    * URL to site to fund the podcast  See the [podcast namespace spec](https://podcastindex.org/namespace/1.0#funding) for more information. 
    */
    'url'?: string;
    /**
    * Description of `url`  See the [podcast namespace spec](https://podcastindex.org/namespace/1.0#funding) for more information. 
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Funding.attributeTypeMap;
    }
}

