/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';
import { QueryId } from './queryId';
import { Status } from './status';
import { Value } from './value';

export class InlineResponse20017 {
    'status'?: Status;
    'query'?: QueryId;
    'value'?: Value;
    /**
    * Description of the response 
    */
    'description'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "Status"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "QueryId"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Value"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20017.attributeTypeMap;
    }
}

