/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';
import { ItemPodcastRandom } from './itemPodcastRandom';
import { Status } from './status';

export class InlineResponse20012 {
    'status'?: Status;
    /**
    * List of episodes matching request 
    */
    'episodes'?: Array<ItemPodcastRandom>;
    /**
    * Number of items returned in request 
    */
    'count'?: number;
    /**
    * Value of `max` parameter passed to request. 
    */
    'max'?: number;
    /**
    * Description of the response 
    */
    'description'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "Status"
        },
        {
            "name": "episodes",
            "baseName": "episodes",
            "type": "Array<ItemPodcastRandom>"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20012.attributeTypeMap;
    }
}

