/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';
import { EpisodeObject } from './episodeObject';
import { Status } from './status';

export class InlineResponse20011 {
    'status'?: Status;
    /**
    * The internal PodcastIndex.org episode ID. 
    */
    'id'?: number;
    'episode'?: EpisodeObject;
    /**
    * Description of the response 
    */
    'description'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "Status"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "episode",
            "baseName": "episode",
            "type": "EpisodeObject"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20011.attributeTypeMap;
    }
}

