/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';

/**
* Tell other podcast platforms whether they are allowed to import this feed. A value of 1 means that any attempt to import this feed into a new platform should be rejected. Contains the value of the feed\'s channel-level `podcast:locked` tag where:    - 0: \'no\'   - 1: \'yes\' 
*/
export enum Locked {
    NUMBER_0 = <any> 0,
    NUMBER_1 = <any> 1
}
