/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';
import { TypeV4v } from './typeV4v';

/**
* Description of the method for providing \"Value for Value\" payments 
*/
export class ModelV4v {
    'type'?: TypeV4v;
    /**
    * Method for sending payment 
    */
    'method'?: string;
    /**
    * Suggested amount per second of playback to send. Unit is specific to the `type`. 
    */
    'suggested'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TypeV4v"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string"
        },
        {
            "name": "suggested",
            "baseName": "suggested",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ModelV4v.attributeTypeMap;
    }
}

