/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';

/**
* Type of source feed where:    - 0: RSS   - 1: Atom 
*/
export enum Type {
    NUMBER_0 = <any> 0,
    NUMBER_1 = <any> 1
}
