/**
 * PodcastIndex.org API
 *
 * OpenAPI spec version: 1.4.0
 * Contact: info@podcastindex.org
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { RequestFile } from './models';
import { DestinationV4v } from './destinationV4v';
import { ModelV4v } from './modelV4v';

/**
* Information for supporting the podcast via one of the \"Value for Value\" methods.  Examples:   - `lightning` value type: https://api.podcastindex.org/api/1.0/podcasts/byfeedid?id=169991&pretty   - `webmonetization` value type: https://api.podcastindex.org/api/1.0/podcasts/byfeedid?id=779873&pretty 
*/
export class Value {
    'model'?: ModelV4v;
    /**
    * List of destinations where \"Value for Value\" payments should be sent. 
    */
    'destinations'?: Array<DestinationV4v>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "model",
            "baseName": "model",
            "type": "ModelV4v"
        },
        {
            "name": "destinations",
            "baseName": "destinations",
            "type": "Array<DestinationV4v>"
        }    ];

    static getAttributeTypeMap() {
        return Value.attributeTypeMap;
    }
}

